name: workflow 2
# clone a repo using actions/checkout@v3
on: push

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # - name: list file
        # run: ls
      - name: Check Node version
        run: node -v