name: workflow 2
# clone a repo using actions/checkout@v3
on: push

jobs:

  say-hello:
    runs-on: ubuntu-latest

    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v3

      - name: list file
        run: ls